version: '3.3'

services:
  djangoblog:
    restart: always
    image: kelequy/djangoblog
    ports:
      - "8000:8000"
    volumes:
      - ./collectedstatic:/code/DjangoBlog/collectedstatic
    environment:
      - DJANGO_MYSQL_DATABASE=djangoblog
      - DJANGO_MYSQL_USER=root
      - DJANGO_MYSQL_PASSWORD=bigsixisme
      - DJANGO_MYSQL_HOST=192.168.3.35
      - DJANGO_MYSQL_PORT=3306
    container_name: djangoblog
    links:
      - memcached
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./bin/nginx.conf:/etc/nginx/nginx.conf
      - ./collectedstatic:/code/DjangoBlog/collectedstatic
    links:
      - djangoblog:djangoblog
    container_name: nginx

  memcached:
    restart: always
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"

